#Instalação

In [1]:
#!pip install numpy

#Importação

In [2]:
import numpy
numpy

<module 'numpy' from '/home/matheus/Desktop/gama_magalu/.venv/lib/python3.10/site-packages/numpy/__init__.py'>

# Lista vs Numpy

In [3]:
lista = [1,2,3,4,5]
array = numpy.array([1,2,3,4,5])
type(lista), type(array)

(list, numpy.ndarray)

In [4]:
lista = list(range(1000))
array = numpy.array(lista, dtype=int)

In [5]:
import sys
sys.getsizeof(lista)

8056

In [6]:
sys.getsizeof(array)

8112

In [7]:
array.ndim

1

In [8]:
len(lista)

1000

In [9]:
semestre = [[10,6,4,8], [5,6,5,6], [3,6,7,9]]
s_array = numpy.array(semestre)

In [10]:
semestre

[[10, 6, 4, 8], [5, 6, 5, 6], [3, 6, 7, 9]]

In [11]:
s_array

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6],
       [ 3,  6,  7,  9]])

In [12]:
#s_array[0][0] = 'matheus'
semestre[0][0] = 10
semestre

[[10, 6, 4, 8], [5, 6, 5, 6], [3, 6, 7, 9]]

# Básico Numpy

In [13]:
# Tipo de dado do array
s_array.dtype

dtype('int64')

In [14]:
# dimensões do array
s_array.ndim

2

In [64]:
#tamanho do array
s_array.size

12

In [15]:
s_array+2

array([[12,  8,  6, 10],
       [ 7,  8,  7,  8],
       [ 5,  8,  9, 11]])

In [16]:
s_array-2

array([[8, 4, 2, 6],
       [3, 4, 3, 4],
       [1, 4, 5, 7]])

In [17]:
s_array/2

array([[5. , 3. , 2. , 4. ],
       [2.5, 3. , 2.5, 3. ],
       [1.5, 3. , 3.5, 4.5]])

In [18]:
s_array * 2

array([[20, 12,  8, 16],
       [10, 12, 10, 12],
       [ 6, 12, 14, 18]])

In [19]:
s_array % 2 == 0

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [20]:
s_array

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6],
       [ 3,  6,  7,  9]])

In [21]:
apoio = semestre.copy()
for notas in range(len(semestre)):
  for nota in range(len(semestre[notas])):
    apoio[notas][nota] = semestre[notas][nota] % 2 == 0

apoio

[[True, True, True, True],
 [False, True, False, True],
 [False, True, False, False]]

In [22]:
s_array % 2 == 0

array([[ True,  True,  True,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [23]:
s_array

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6],
       [ 3,  6,  7,  9]])

In [24]:
s_array[1, [0,1,-1]].tolist()

[5, 6, 6]

In [25]:
semestre[1][0:2] + [semestre[1][3]]

[False, True, True]

In [26]:
s_array.astype(float)

array([[10.,  6.,  4.,  8.],
       [ 5.,  6.,  5.,  6.],
       [ 3.,  6.,  7.,  9.]])

# Criação de Arrays

In [27]:
import numpy as np
#numpy.array
np.zeros([2, 3, 4])#2x3x4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.ones([2, 3, 4])#2x3x4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
np.full([2, 3, 4], 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [30]:
notas = np.random.randint(low=0, high=11, size=[2, 3, 4])
notas

array([[[ 4,  0,  1,  5],
        [ 3, 10,  0,  2],
        [ 9,  2,  9,  5]],

       [[ 9,  8,  9,  3],
        [ 1,  3,  6,  5],
        [ 1,  5,  8,  9]]])

In [31]:
np.full_like(notas, 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [32]:
np.arange(start=0, stop=24).reshape([2,3,4]) 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
2*3*4, notas.size

(24, 24)

In [34]:
exemplo = np.zeros([2,3,4]) #[arquivo, planilha, linha, coluna]
exemplo[1] = 1
exemplo

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
exemplo

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
# Exemplo de números decimais aleatórios numa matriz entre 0 e 1 (não incluso)
np.random.rand(2,2) # numeros aleatórios entre [0, 1)

array([[0.07363085, 0.52331368],
       [0.49306378, 0.68258431]])

In [47]:
# Exemplo de números decimais aleatórios numa matriz 2x2 de 0 a 50 (não incluso)
np.random.rand(2,2) #[0, 1) * 50-> [0, 50) 0..49.99999999
np.random.rand(2,2)*50 

array([[ 3.02436684, 23.99060157],
       [43.69799442, 14.1981677 ]])

In [66]:
#Geração de array baseado em uma lista
# Exemplo de geração textos aleatórios

opcoes = ['azul', 'vermelho', 'verde', 'amarelo']
cores = np.random.choice(opcoes, size=[5,5])
cores

array([['vermelho', 'azul', 'amarelo', 'amarelo', 'verde'],
       ['vermelho', 'verde', 'vermelho', 'vermelho', 'verde'],
       ['amarelo', 'vermelho', 'vermelho', 'amarelo', 'azul'],
       ['verde', 'azul', 'vermelho', 'amarelo', 'verde'],
       ['verde', 'vermelho', 'amarelo', 'verde', 'amarelo']], dtype='<U8')

In [75]:
#cores.ravel()
lista_cores = cores.reshape([25])
lista_cores

array(['vermelho', 'azul', 'amarelo', 'amarelo', 'verde', 'vermelho',
       'verde', 'vermelho', 'vermelho', 'verde', 'amarelo', 'vermelho',
       'vermelho', 'amarelo', 'azul', 'verde', 'azul', 'vermelho',
       'amarelo', 'verde', 'verde', 'vermelho', 'amarelo', 'verde',
       'amarelo'], dtype='<U8')

In [69]:
cores == 'verde'
cores[cores == 'verde'].size
len(cores[cores == 'verde'])

print(f'''
Seguem as quantidade de cada cor:
Azul: {cores[cores=='azul'].size}
vermelho: {len(cores[cores=='vermelho'])}
verde: {cores[cores=='verde'].size}
amarelo: {len(cores[cores=='amarelo'])}
Total: {cores.size}
''')


Seguem as quantidade de cada cor:
Azul: 3
vermelho: 8
verde: 7
amarelo: 7
Total: 25



In [80]:
# Exemplo com pandas
import pandas as pd
serie_cor = pd.Series(lista_cores, name='cores')
print(f'Total: {serie_cor.count()}')
serie_cor.value_counts()

Total: 25


vermelho    8
amarelo     7
verde       7
azul        3
Name: cores, dtype: int64

In [38]:
# repete o array para alguma das dimensões
# lembrando que, se quiser repetir para baixo, o array tem que ter 2 dimensões
array = np.array([[0., 0., 0., 0.], [1,1,1,1]])
array
# [linha, coluna]
np.repeat(array, 4, axis=0) # eixo das linhas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.repeat(array, 2, axis=1) # eixo das colunas

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

np.vstack([array1, array2]) # concatenar arrays na vertical


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
#np.concatenate([array1, array2])
np.hstack([array1, array2]) # concatenar arrays na horizontal

array([1, 2, 3, 4, 5, 6, 7, 8])

# Seleção e Máscaras

In [40]:
#list(range(0, 36))
#list(range(36))
import numpy as np

'''
array = np.arange(0,36)
array = array.reshape([6,6])
array
'''

array = np.arange(0,36).reshape([6,6])
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [41]:
#[arquivo, planilha, linha, coluna]
#[linha, coluna]
# linha
array[2] # como a primeira dimensão é linha, seleciona a linha de índice 2
#array[2, :]

array([12, 13, 14, 15, 16, 17])

In [42]:
#coluna
array[:, 2] # os : pegam todas as linhas, e seleciona a coluna de índice 2

array([ 2,  8, 14, 20, 26, 32])

In [43]:
#array[2:-1, 1:-2]
array[2:5, 1:4] # Seleciona da linha 2 a 5(não incluso), e linhas 1 a 4(não incluso)

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [44]:
array[:, [1,3,5]] # : seleciona todas as linhas, e as colunas 1,3,5

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [45]:
array[[0,2,4], :] # seleciona as linhas 0, 2, 4 e todas as colunas
#array[::2,:]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [46]:
#[linha, coluna]
#[inicio:fim_nao_incluso:passo, inicio:fim_nao_incluso:passo]
array[1:5:2,:] # seleciona da linha 1 a 5 (não incluso) andando de 2 em 2, e todas as colunas

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])